// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sgvshurptmccqixrutpc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNndnNodXJwdG1jY3FpeHJ1dHBjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI2ODU2MjUsImV4cCI6MjA1ODI2MTYyNX0.Tfws4p00o4_tJscyO22eXCf2jseyh1_azLKObvom6Xk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);